### ISSUE TITLE
Question Regarding Table 4 vs 5 vs B

### ISSUE THREAD

**Issue by Divadi** [zpbao/MoTok#1]
Hello - thank you for open sourcing your work! I just had a quick question regarding the FG ARI performance on KITTI.

In the tables below:
![image](https://github.com/zpbao/MoTok/assets/17109672/044a5999-ff05-4bf6-9287-cd018ec50c07)
![image](https://github.com/zpbao/MoTok/assets/17109672/ece068e8-da9a-45fb-8a95-2ca2baecb858)
It seems that each table has slightly different numbers for FG ARI performance on KITTI. Am I correct in understanding:

- All results on KITTI are per-frame FG ARI (since I think the 200 frame test data does not have temporal information)
- Table B is conducted with a ViT backbone
- What is the difference between Table 4 and 5? (60.6 vs 64.4)

Thank you in advance, and I apologize if I have missed a detail in the paper.

**Comment by zpbao** [comment]
Hi Jinhyung,

For your questions, in summary: table 4 is for TRI-PD, not KITTI; for Table B, we use a ViT backbone.

For the 3 key points you listed:
1) Yes, we measure per-frame FG ARI for KITTI;
2) Table B shows the results with a ViT backbone;
3) Table 4 is for TRI-PD but Table 5 is for KITTI.

Let me know if you have further questions!

Thanks,
Zhipeng
